# Generated by Django 5.1.2 on 2024-10-31 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('path', models.FileField(upload_to='uploads/')),
                ('extension', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.CharField(choices=[('NOT_DELETED', 'NOT_DELETED'), ('CASCADE_DELETED', 'CASCADE_DELETED'), ('PERMANENTLY_DELETED', 'PERMANENTLY_DELETED')], default='NOT_DELETED', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['user', 'created_at'],
            },
        ),
    ]
