# Generated by Django 5.1.2 on 2024-10-31 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.CharField(choices=[('NOT_DELETED', 'NOT_DELETED'), ('CASCADE_DELETED', 'CASCADE_DELETED'), ('PERMANENTLY_DELETED', 'PERMANENTLY_DELETED')], default='NOT_DELETED', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recognize',
            },
        ),
    ]
